spring:
  application:
    name: task-list
  datasource:
    url: jdbc:mysql://localhost:3306/tasks?createDatabaseIfNotExist=true
    username: root
    password: 159263
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

